/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import type {
  Bus,
} from '../models';
import {
    BusFromJSON,
    BusToJSON,
} from '../models';

export interface GetUpcomingStopsRequest {
    id: number;
}

/**
 * 
 */
export class BusesApi extends runtime.BaseAPI {

    /**
     * Retrieves a list of upcoming stops for a specific bus, identified by its ID.
     * Retrieve upcoming stops for a bus.
     */
    async getUpcomingStopsRaw(requestParameters: GetUpcomingStopsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Bus>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getUpcomingStops().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/buses/{id}/stops`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BusFromJSON));
    }

    /**
     * Retrieves a list of upcoming stops for a specific bus, identified by its ID.
     * Retrieve upcoming stops for a bus.
     */
    async getUpcomingStops(requestParameters: GetUpcomingStopsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Bus>> {
        const response = await this.getUpcomingStopsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
