/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import type {
  Station,
  Train,
} from '../models';
import {
    StationFromJSON,
    StationToJSON,
    TrainFromJSON,
    TrainToJSON,
} from '../models';

export interface GetArrivalsRequest {
    stationId: number;
}

/**
 * 
 */
export class StationsApi extends runtime.BaseAPI {

    /**
     * Retrieves a list of upcoming train arrivals for a specific station, identified by the station ID.
     * Retrieve upcoming train arrivals for a station.
     */
    async getArrivalsRaw(requestParameters: GetArrivalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Train>>> {
        if (requestParameters['stationId'] == null) {
            throw new runtime.RequiredError(
                'stationId',
                'Required parameter "stationId" was null or undefined when calling getArrivals().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/stations/{stationId}/arrivals`.replace(`{${"stationId"}}`, encodeURIComponent(String(requestParameters['stationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrainFromJSON));
    }

    /**
     * Retrieves a list of upcoming train arrivals for a specific station, identified by the station ID.
     * Retrieve upcoming train arrivals for a station.
     */
    async getArrivals(requestParameters: GetArrivalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Train>> {
        const response = await this.getArrivalsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the list of all available train stations in the system.
     * Retrieve the list of train stations.
     */
    async getStationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Station>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/stations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StationFromJSON));
    }

    /**
     * Retrieves the list of all available train stations in the system.
     * Retrieve the list of train stations.
     */
    async getStations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Station>> {
        const response = await this.getStationsRaw(initOverrides);
        return await response.value();
    }

}
