/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import type {
  Train,
} from '../models';
import {
    TrainFromJSON,
    TrainToJSON,
} from '../models';

export interface GetUpcomingStationsRequest {
    run: number;
}

/**
 * 
 */
export class TrainsApi extends runtime.BaseAPI {

    /**
     * Retrieves a list of upcoming stations for a specific train, identified by its run number.
     * Retrieve upcoming stations for a train run.
     */
    async getUpcomingStationsRaw(requestParameters: GetUpcomingStationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Train>>> {
        if (requestParameters['run'] == null) {
            throw new runtime.RequiredError(
                'run',
                'Required parameter "run" was null or undefined when calling getUpcomingStations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/trains/{run}/stations`.replace(`{${"run"}}`, encodeURIComponent(String(requestParameters['run']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrainFromJSON));
    }

    /**
     * Retrieves a list of upcoming stations for a specific train, identified by its run number.
     * Retrieve upcoming stations for a train run.
     */
    async getUpcomingStations(requestParameters: GetUpcomingStationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Train>> {
        const response = await this.getUpcomingStationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
