/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.ts';
/**
 * Represents a train station and its details.
 * @export
 * @interface Station
 */
export interface Station {
    /**
     * The unique identifier of the station.
     * @type {number}
     * @memberof Station
     */
    id: number;
    /**
     * The name of the station.
     * @type {string}
     * @memberof Station
     */
    name: string;
}

/**
 * Check if a given object implements the Station interface.
 */
export function instanceOfStation(value: object): value is Station {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StationFromJSON(json: any): Station {
    return StationFromJSONTyped(json, false);
}

export function StationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Station {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

  export function StationToJSON(json: any): Station {
      return StationToJSONTyped(json, false);
  }

  export function StationToJSONTyped(value?: Station | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

